version: "3.7"

services:
  api_container:
    container_name: bdbackend
    hostname: bdbackend
    image: mariadb
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes: - ~/.MariaDBData/mariadb/bdbackend:/var/lib/mysql
    ports:
      - 3306:3306
      # - 27018:3306
    environment:
      MYSQL_ROOT_PASSWORD: root # root password
      MYSQL_DATABASE: api_database # database
      # MYSQL_USER: root # database user
      MYSQL_PASSWORD: root # database user password
